# Generated by Django 2.2.1 on 2019-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspiece_title', models.CharField(max_length=100)),
                ('newspiece_content', models.TextField()),
                ('hupu_id', models.IntegerField()),
            ],
        ),
    ]
