# Generated by Django 2.2.1 on 2019-09-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_invertedindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invertedindex',
            old_name='value_word',
            new_name='value_each_article',
        ),
    ]
