# Generated by Django 2.2.1 on 2019-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190904_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=10)),
                ('enter_NBA_time', models.CharField(max_length=10)),
                ('stadium', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('home_page', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=10)),
                ('logo_url', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=100)),
                ('rosters', models.TextField()),
            ],
        ),
    ]
