# Generated by Django 2.2.1 on 2019-09-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspiece',
            name='newspiece_source',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspiece',
            name='newspiece_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
